### ISSUE TITLE
EIP712 message UX/UI

### ISSUE THREAD

**Issue by bxmmm1** [tangem/tangem-app-ios-old#2725]
Can you please make it look nice so that before clicking `Sign` the user can copy & paste values from the signature so that it is easier to double-check everything?

The EIP712 Message looks hideous. Here is an example of the EIP712 Permit message on CowSwap.
![image](https://github.com/tangem/tangem-app-ios/assets/28648109/46a8af04-1dfe-4ad6-a3a8-040dc92d61eb)

**Comment by tureck1y** [comment]
Hello! We have plans about a complete redesign of WalletConnect UI soon. Thank you.
