### ISSUE TITLE
Feature Request: Support Pulsechain (Ethereum fork)

### ISSUE THREAD

**Issue by IronSight87** [tangem/tangem-app-ios-old#2801]
Pulsechain is a fork of Ethereum and the 11th biggest chain by TVL and 24h volume (S1). Meaning it is bigger than already supported chains like Cardano, KAVA and Kujira.
It also has a growing community of 125k followers on Twitter (S2).

Sources:
- S1: https://defillama.com/chains
- S2: https://x.com/pulsechaincom

**Comment by tureck1y** [comment]
Yes. We have plans to add this network in the very near future.

**Comment by IronSight87** [comment]
@tureck1y Thanks for your feedback. Any specific date for "in the very near future"?

**Comment by tureck1y** [comment]
Within 1-2 months I hope

**Comment by IronSight87** [comment]
@tureck1y 
Oh wow. I thought it would take less time as all needed code is already there.
It would make sense to provide your users with a "add network" interface like MetaMask. The user enters RPC url, chain id, symbol, explorer and is good to go. Just a recommendation so that users like me don't have to bother you ;)

Thanks again!
