### ISSUE TITLE
Integrate SwapKit (THORChain, Chainflip & Maya Protocol) for cross-chain swaps

### ISSUE THREAD

**Issue by GiMa-Maya** [tangem/tangem-app-ios-old#3155]
SwapKit is an aggregator SDK that combines the decentralised and permissionless cross-chain swaps of THORChain, Chainflip, ann soon Maya Protocol. These protocols are connected to single chain dex's such as Uniswap, Sushiswap, 1inch, 0x, Kyber, TraderJoe, Woofi and Pancakeswap. 

Cross-chain swaps between the following chains are supported: Bitcoin, Bitcoin Cash, Litecoin, Dogecoin, Dash, Ethereum, Arbitrum, Avalanche, Binance Smart Chain, THORChain, MAYAChain, Atom, Kujira, and Polkadot. 
Soon, Solana, Radix, Zcash, and Cardano support will follow. 

Tangem can earn affiliate fees through these swaps. 

Benefits of integrating SwapKit:
- SwapKit runs infra and support
- Dex aggregation routes
- 1 integration instead of integrating all these chains and protocols separately. 
- Earn fees when users do swaps

Happy to tell you more about it in a call!
https://swapkit.dev

**Comment by tureck1y** [comment]
Thank you for reaching out and for your suggestion!

I've passed the information along to the Tangem Express team, who are responsible for integrating exchange providers.
