### ISSUE TITLE
Some error on cocoapods depedency.

### ISSUE THREAD

**Issue by YangYouYong** [tangem/tangem-app-ios-old#35]
For this project , web3swift depends on PromiseKit 6.8.4.
Unfortunately, PromiseKit 6.8.4 and 6.8.5 missed the PromiseKit.podspec file in their project.
Users cannot install the pods.
Can you team fix this issue on your project?

**Comment by tureck1y** [comment]
Hi! We can't confirm any problems with cocoapods right now. The project compiles successfully. You can find a project with an updated dependencies in the develop branch. Anyway, we will remove most of our dependencies in the near future, including web3swift. 

Try to remove podfile.lock in your project and run `pod install`
