### ISSUE TITLE
Translation error in French

### ISSUE THREAD

**Issue by philippe-tressard** [tangem/tangem-app-ios-old#3662]
Hello,
Many errors of translation in French from iOS-app : 

Main screen : 
wallet : portefeuille 
cards : cartes
Manage tokens : Gérer vos jetons

…
Connect to dApps : Connecter à dApps
Add New wallet : Ajoute nouveau portefeuille 
App settings : Paramètres App

when you choose a token (not manage)
Receive : Recevoir
Swap : Échange
Buy : Achète
Sell : Vend
…. Market price : … prix du marché

**Comment by tureck1y** [comment]
Thank you for being so helpful. We have passed on your comments to our translators.
