### ISSUE TITLE
Support for Scroll

### ISSUE THREAD

**Issue by k-moonblade** [tangem/tangem-app-ios-old#4111]
Hi. I noticed that by walletconnect - connection to the Scroll blockhain is not available. 

Should I open an issue at the SDK repo instead? 

Thanks

**Comment by jsdude0220** [comment]
@RoyTimes

**Comment by tureck1y** [comment]
This blockchain is not supported yet, so the connection via WC does not work. There are no plans to add this blockchain shortly. I will pass it on to the team responsible for blockchain analysis.
