### ISSUE TITLE
Bug with offline wallet setup

### ISSUE THREAD

**Issue by VincentBounce** [tangem/tangem-app-ios-old#4214]
Very good hardware wallet, congratulations to the team!

But I just figured out a bug, I tried to create my wallet offline without any connexion to ensure nothing related to my private key is sent during this process.

**It does work only for the primary card, impossible to add the backup card.**

**The normal behavior should be to offer to bypass the online certificate check for the backup card as it is offered for the primary card.** But as you can see in this video, it's not offered. The only way to configure the backup card is to go back online.

https://github.com/user-attachments/assets/fe77050a-862f-42d3-aeb2-cf700df2facf

**Comment by tureck1y** [comment]
You don't need an internet connection to generate/import the seed phrase, thus, a phone without Wi-Fi or a SIM card can be used at this step. However, an internet connection is necessary when creating a backup to download the certificates. Even so, you can initiate the seed phrase import on one device and proceed with the backup on another device that has internet access.
It is irrelevant whether there is an internet connection on the phone, as the seed phrase is generated directly on the device and does not require an internet connection. Nonetheless, some users express concerns about security, fearing that the seed could be transmitted from the phone. We would like to clarify that this is not the case. The seed is not stored in any location. Instead, it is used to generate a private key, which is subsequently transferred to the card.

 More information can be found here:

https://tangem.com/en/blog/post/how-tangem-wallet-backs-up-private-keys/
https://tangem.com/en/blog/post/setup-without-seed-phrase/
