### ISSUE TITLE
Some networks are inaccessible

### ISSUE THREAD

**Issue by byackee** [tangem/tangem-app-ios-old#4376]
Hi,

Since 1 or 2 last updated I have this message and no total balance

If some network not working, the app need to show available balance

![image](https://github.com/user-attachments/assets/8e46f1a4-f381-49c0-9e8a-01731e7cc555)

**Comment by tureck1y** [comment]
We can't show an incomplete balance. You may have a token in the BEP2 network. Developers have disabled this network, and you can hide this token. We will update the application, and this network will no longer be taken into account.

**Comment by byackee** [comment]
Yes you right 😃, I don't saw the default token...

Thank you, it's working
